version: '2'
services:
  nginx:
    container_name: nginx
    image: feeldburn-nginx
    build: 
      context: .
      dockerfile: nginx.dockerfile
    volumes:
      - ./web/dist/:/var/www/public/
    links:
        - node-1:node-1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nodeapp-network
  node-1:
    container_name: feeldburn-api
    image: feeldburn-api
    build:
      context: ./api
      dockerfile: node.dockerfile
    volumes:
      - ./api/:/var/www/
    links:
      - feeldburnmongodb:feeldburnmongodb
    ports:
      - "3000:3000"
      - "7000:7000"
    networks:
      - nodeapp-network
  feeldburnmongodb:
    container_name: feeldburnmongodb
    image: mongo:latest
    #command: mongod --auth
    command: mongod
    ports:
      - "27017:27017"
    networks:
      - nodeapp-network
    volumes:
      - '/data/db:/data/db'  
networks:
  nodeapp-network:
    driver: bridge
