version: '2'
services:
  nginx:
    container_name: nginx
    image: feeldburn-nginx
    build: 
      context: .
      dockerfile: nginx.dockerfile
    links:
        - node-1:node-1
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nodeapp-network
  node-1:
    container_name: feeldburn-api
    image: feeldburn-api
    build:
      context: ./api
      dockerfile: node.dockerfile
    links:
      - feeldburnmongodb:feeldburnmongodb
    ports:
      - "3000:3000"
      - "7000:7000"
    networks:
      - nodeapp-network
  feeldburnmongodb:
    container_name: feeldburnmongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - nodeapp-network
    volumes:
      - '/skraemer/dockerVolMongo:/data/db'  
networks:
  nodeapp-network:
    driver: bridge
