FROM node

ENV HOME=/usr/src/app
RUN mkdir -p $HOME
RUN mkdir -p $HOME/client/dist
WORKDIR $HOME
COPY package.json /usr/src/app
COPY index.js /usr/src/app
COPY /client/dist /usr/src/app/client/dist
RUN npm install

EXPOSE 4200

CMD ["node", "index.js"]