version: '2'
services:
  web-1:
    container_name: feeldburn-web
    image: feeldburn-web
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "4200:4200"
    command: npm start
    networks:
      - nodeapp-network
networks:
  nodeapp-network:
    driver: bridge